name = "munich"
license = "MIT"
licenselink = "https://github.com/gmixa/hugo-theme-munich/blob/master/LICENSE.md"
description = "Simple and clean blog theme for hugo"
homepage = "https://github.com/gmixa/hugo-theme-munich"
tags = ["blog", "tags", "bootstrap", "multilingual", "clean", "minimal", "disqus", "font awesome", "mobile"]
repo = "https://github.com/gmixa/hugo-theme-munich"
min_version = "0.57"

[author]
	name = "Gerald Mixa"
	homepage = "https://mixas.de"

[original]
	author = "Hauke Stieler"
	name = "hamburg"
	homepage = "https://hauke-stieler.de/"
	repo = "https://github.com/hauke96/hugo-theme-hamburg"
